# Generated by Django 3.1.5 on 2021-01-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210113_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Column Number', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='column_number',
            field=models.ForeignKey(help_text='Select art type', null=True, on_delete=django.db.models.deletion.RESTRICT, to='index.columnnumber'),
        ),
    ]
