# Generated by Django 3.1.5 on 2021-01-13 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210113_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='column_number',
            field=models.ForeignKey(default=1, help_text='Select art type', null=True, on_delete=django.db.models.deletion.RESTRICT, to='index.columnnumber'),
        ),
    ]
