# Generated by Django 3.1.5 on 2021-01-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210116_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='path',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='name',
            field=models.TextField(max_length=600),
        ),
    ]
