# Generated by Django 3.1.5 on 2021-01-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210117_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='name',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
